// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(LiverpoolDbContext))]
    [Migration("20251229132216_AttendeeStatus")]
    partial class AttendeeStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Common.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Text = "Indoor"
                        },
                        new
                        {
                            Id = 2L,
                            Text = "Outdoor"
                        },
                        new
                        {
                            Id = 3L,
                            Text = "Online"
                        },
                        new
                        {
                            Id = 4L,
                            Text = "Hybrid"
                        },
                        new
                        {
                            Id = 5L,
                            Text = "Active"
                        },
                        new
                        {
                            Id = 6L,
                            Text = "Relaxed"
                        },
                        new
                        {
                            Id = 7L,
                            Text = "Casual"
                        },
                        new
                        {
                            Id = 8L,
                            Text = "High Energy"
                        },
                        new
                        {
                            Id = 9L,
                            Text = "Low Effort"
                        },
                        new
                        {
                            Id = 10L,
                            Text = "Networking"
                        },
                        new
                        {
                            Id = 11L,
                            Text = "Social"
                        },
                        new
                        {
                            Id = 12L,
                            Text = "Friends"
                        },
                        new
                        {
                            Id = 13L,
                            Text = "Professional"
                        },
                        new
                        {
                            Id = 14L,
                            Text = "Community"
                        },
                        new
                        {
                            Id = 15L,
                            Text = "Workshop"
                        },
                        new
                        {
                            Id = 16L,
                            Text = "Meetup"
                        },
                        new
                        {
                            Id = 17L,
                            Text = "Presentation"
                        },
                        new
                        {
                            Id = 18L,
                            Text = "Discussion"
                        },
                        new
                        {
                            Id = 19L,
                            Text = "Training"
                        },
                        new
                        {
                            Id = 20L,
                            Text = "Brainstorming"
                        },
                        new
                        {
                            Id = 21L,
                            Text = "Q&A"
                        },
                        new
                        {
                            Id = 22L,
                            Text = "Sports"
                        },
                        new
                        {
                            Id = 23L,
                            Text = "Wellness"
                        },
                        new
                        {
                            Id = 24L,
                            Text = "Fitness"
                        },
                        new
                        {
                            Id = 25L,
                            Text = "Food & Drinks"
                        },
                        new
                        {
                            Id = 26L,
                            Text = "Music"
                        },
                        new
                        {
                            Id = 27L,
                            Text = "Art & Culture"
                        },
                        new
                        {
                            Id = 28L,
                            Text = "Tech"
                        },
                        new
                        {
                            Id = 29L,
                            Text = "Gaming"
                        },
                        new
                        {
                            Id = 30L,
                            Text = "Outdoors & Nature"
                        },
                        new
                        {
                            Id = 31L,
                            Text = "Travel"
                        },
                        new
                        {
                            Id = 32L,
                            Text = "Short Event"
                        },
                        new
                        {
                            Id = 33L,
                            Text = "Long Event"
                        },
                        new
                        {
                            Id = 34L,
                            Text = "Morning"
                        },
                        new
                        {
                            Id = 35L,
                            Text = "Afternoon"
                        },
                        new
                        {
                            Id = 36L,
                            Text = "Evening"
                        },
                        new
                        {
                            Id = 37L,
                            Text = "Night"
                        },
                        new
                        {
                            Id = 38L,
                            Text = "Weekend"
                        },
                        new
                        {
                            Id = 39L,
                            Text = "Weekday"
                        },
                        new
                        {
                            Id = 40L,
                            Text = "Beginner Friendly"
                        },
                        new
                        {
                            Id = 41L,
                            Text = "Intermediate"
                        },
                        new
                        {
                            Id = 42L,
                            Text = "Advanced"
                        },
                        new
                        {
                            Id = 43L,
                            Text = "Family Friendly"
                        },
                        new
                        {
                            Id = 44L,
                            Text = "Adults Only"
                        },
                        new
                        {
                            Id = 45L,
                            Text = "Inclusive"
                        },
                        new
                        {
                            Id = 46L,
                            Text = "Small Group"
                        },
                        new
                        {
                            Id = 47L,
                            Text = "Large Group"
                        },
                        new
                        {
                            Id = 48L,
                            Text = "One-on-One"
                        },
                        new
                        {
                            Id = 49L,
                            Text = "Open Event"
                        },
                        new
                        {
                            Id = 50L,
                            Text = "Invite Only"
                        },
                        new
                        {
                            Id = 51L,
                            Text = "Chill"
                        },
                        new
                        {
                            Id = 52L,
                            Text = "Fun"
                        },
                        new
                        {
                            Id = 53L,
                            Text = "Serious"
                        },
                        new
                        {
                            Id = 54L,
                            Text = "Creative"
                        },
                        new
                        {
                            Id = 55L,
                            Text = "Focused"
                        },
                        new
                        {
                            Id = 56L,
                            Text = "Free"
                        },
                        new
                        {
                            Id = 57L,
                            Text = "Paid"
                        },
                        new
                        {
                            Id = 58L,
                            Text = "Bring Your Own"
                        },
                        new
                        {
                            Id = 59L,
                            Text = "Beginner Welcome"
                        },
                        new
                        {
                            Id = 60L,
                            Text = "Recurring Event"
                        },
                        new
                        {
                            Id = 61L,
                            Text = "One-Time Event"
                        },
                        new
                        {
                            Id = 62L,
                            Text = "Local"
                        },
                        new
                        {
                            Id = 63L,
                            Text = "International"
                        });
                });

            modelBuilder.Entity("Api.Entities.Event.Attendee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendee");
                });

            modelBuilder.Entity("Api.Entities.Event.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Api.Entities.Event.EventTag", b =>
                {
                    b.Property<long>("TagId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.HasKey("TagId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("Api.Entities.User.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureBase64")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Entities.User.UserRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttendeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("Api.Entities.Event.Attendee", b =>
                {
                    b.HasOne("Api.Entities.Event.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Entities.Event.Event", b =>
                {
                    b.HasOne("Api.Entities.User.User", "Creator")
                        .WithMany("Events")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Api.Entities.Event.EventTag", b =>
                {
                    b.HasOne("Api.Entities.Event.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Common.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Api.Entities.User.UserRating", b =>
                {
                    b.HasOne("Api.Entities.Event.Attendee", "Attendee")
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Entities.Event.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Api.Entities.User.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendee");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Entities.Event.Event", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Api.Entities.User.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
